name: CI
on: [push]
env:
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Apply filters
        uses: dorny/paths-filter@v2
        id: filters
        with:
          filters: |
            ass_1:
              - '01_basics/**'
            ass_2:
              - '02_memory/**'
            ass_3:
              - '03_oo/**'
            ass_4:
              - '04_advanced/**'
            ass_5:
              - '05_c/**'
      - name: Run tests for assignment 1
        if: steps.filters.outputs.ass_1 == 'true'
        run: |
          cd 01_basics
          make test
      - name: Run tests for assignment 2
        if: steps.filters.outputs.ass_2 == 'true'
        run: |
          cd 02_memory
          make test
      - name: Run tests for assignment 3
        if: steps.filters.outputs.ass_3 == 'true'
        run: |
          cd 03_oo
          make test
      - name: Run tests for assignment 4
        if: steps.filters.outputs.ass_4 == 'true'
        run: |
          cd 04_advanced
          make test
      - name: Run tests for assignment 5
        if: steps.filters.outputs.ass_5 == 'true'
        run: |
          cd 05_c
          make test
