name: GitHub Actions Demo
on: [push]
env:
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests for assignment 1
        run: |
          cd 01_basics
          make test
